# Configuration
# logo: "/assets/images/*.jpg"

remote_theme: pmarsceill/just-the-docs
title: C# Programming
description: C# Programming Class
color_scheme: bch

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/

# Footer text for the license
footer_content: "Copyright &copy; 2021 Markus Räisänen. More information about <a href=\"/csharp/license\">the licensing.</a>"
